var buttons = [
  {
    name: "strongOpen",
    innerText: "&lt;strong&gt;",
    classes: ["html", "drag", "button"],
    tag: "opening",
    type: "strong",
  },
  {
    name: "strongClose",
    innerText: "&lt;/strong&gt;",
    classes: ["html", "drag", "button"],
    tag: "closing",
    type: "strong",
  },
  {
    name: "emOpen",
    innerText: "&lt;em&gt;",
    classes: ["html", "drag", "button"],
    tag: "opening",
    type: "em",
  },
  {
    name: "emClose",
    innerText: "&lt;/em&gt;",
    classes: ["html", "drag", "button"],
    tag: "closing",
    type: "em",
  },
  {
    name: "aOpen",
    innerText: "&lt;a&gt;",
    classes: ["html", "drag", "button"],
    tag: "opening",
    type: "a",
  },
  {
    name: "aClose",
    innerText: "&lt;/a&gt;",
    classes: ["html", "drag", "button"],
    tag: "closing",
    type: "a",
  },
  {
    name: "color",
    innerText: "color:",
    classes: ["css", "drag", "button"],
    tag: "keyword",
    type: "purple",
  },
  {
    name: "purple",
    innerText: "purple",
    classes: ["css", "drag", "button"],
    tag: "value",
    type: "purple",
  },
  {
    name: "background",
    innerText: "background:",
    classes: ["css", "drag", "button"],
    tag: "keyword",
    type: "yellow",
  },
  {
    name: "yellow",
    innerText: "yellow",
    classes: ["css", "drag", "button"],
    tag: "value",
    type: "yellow",
  },
  {
    name: "font",
    innerText: "font-family:",
    classes: ["css", "drag", "button"],
    tag: "keyword",
    type: "font",
  },
  {
    name: "pacifico",
    innerText: "\"Pacifico\"",
    classes: ["css", "drag", "button"],
    tag: "value",
    type: "font",
  },
]
