var levels = [
{
name: "Level 1",
textLines: 1,
htmlBuckets: [1],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["strongOpen", "strongClose"],
classesNeeded: [["strongText"]],
},
{
name: "Level 2",
textLines: 1,
htmlBuckets: [1],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["emOpen", "emClose"],
classesNeeded: [["emText"]],
},
{
name: "Level 3",
textLines: 1,
htmlBuckets: [1],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["aOpen", "aClose"],
classesNeeded: [["aText"]],
},
{
name: "Level 4",
textLines: 1,
htmlBuckets: [2],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["emOpen", "emClose", "strongOpen", "strongClose"],
classesNeeded: [["emText", "strongText"]],
},
{
name: "Level 5",
textLines: 1,
htmlBuckets: [2],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["emOpen", "emClose", "aOpen", "aClose"],
classesNeeded: [["emText", "aText"]],
},
{
name: "Level 6",
textLines: 1,
htmlBuckets: [2],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["aOpen", "aClose", "strongOpen", "strongClose"],
classesNeeded: [["aText", "strongText"]],
},
{
name: "Level 7",
textLines: 2,
htmlBuckets: [1, 1],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["aOpen", "aClose", "strongOpen", "strongClose"],
classesNeeded: [["aText"], ["strongText"]],
},
{
name: "Level 12",
textLines: 2,
htmlBuckets: [2, 1],
cssBlocks: 2,
cssSelectors: ["p", "div"],
cssPairs: [1, 2],
buttonsNeeded: ["emOpen", "emClose", "color", "white", "background-color", "border-radius"],
classesNeeded: ["italicText", "whiteText", "roundedCorners"],
}
]
