var levels = [
{
name: "Level 1",
textLines: 1,
htmlBuckets: [1],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["strongOpen", "strongClose"],
classesNeeded: ["strongText"],
},
{
name: "Level 2",
textLines: 1,
htmlBuckets: [1],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["emOpen", "emClose"],
classesNeeded: ["emText"],
},
{
name: "Level 3",
textLines: 1,
htmlBuckets: [1],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["aOpen", "aClose"],
classesNeeded: ["aText"],
},
{
name: "Level 4",
textLines: 1,
htmlBuckets: [2],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["emOpen", "emClose", "strongOpen", "strongClose"],
classesNeeded: ["emText", "strongText"],
},
{
name: "Level 5",
textLines: 1,
htmlBuckets: [2],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["emOpen", "emClose", "aOpen", "aClose"],
classesNeeded: ["emText", "aText"],
},
{
name: "Level 6",
textLines: 1,
htmlBuckets: [2],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["aOpen", "aClose", "strongOpen", "strongClose"],
classesNeeded: ["aText", "strongText"],
},
{
name: "Dummy Level",
textLines: 0,
htmlBuckets: [2],
cssBlocks: 0,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: [],
classesNeeded: [],
},
{
name: "Level 7",
textLines: 0,
htmlBuckets: [],
cssBlocks: 1,
cssSelectors: ["div"],
cssPairs: [1],
buttonsNeeded: ["image", "url"],
classesNeeded: ["imageText"],
},
{
name: "Level 8",
textLines: 1,
htmlBuckets: [1],
cssBlocks: 1,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["color", "purple", "strongOpen", "strongClose"],
classesNeeded: ["strongText", "purpleText"],
},
{
name: "Level 9",
textLines: 1,
htmlBuckets: [2],
cssBlocks: 1,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["color", "purple", "emOpen", "emClose", "aOpen", "aClose"],
classesNeeded: ["emText", "aText", "purpleText"],
},
{
name: "Level 10",
textLines: 1,
htmlBuckets: [1],
cssBlocks: 1,
cssSelectors: ["div"],
cssPairs: [1],
buttonsNeeded: ["background", "yellow", "strongOpen", "strongClose"],
classesNeeded: ["strongText", "yellowText"],
},
{
name: "Level 11",
textLines: 1,
htmlBuckets: [],
cssBlocks: 1,
cssSelectors: ["p"],
cssPairs: [2],
buttonsNeeded: ["family", "pacifico", "color", "purple"],
classesNeeded: ["fontText", "purpleText"],
},
{
name: "Level 12",
textLines: 1,
htmlBuckets: [1],
cssBlocks: 1,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["align", "left", "strongOpen", "strongClose"],
classesNeeded: ["alignText", "strongText"],
},
{
name: "Level 13",
textLines: 1,
htmlBuckets: [1],
cssBlocks: 1,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["align", "left", "emOpen", "emClose"],
classesNeeded: ["alignText", "emText"],
},
{
name: "Level 14",
textLines: 1,
htmlBuckets: [2],
cssBlocks: 1,
cssSelectors: ["p"],
cssPairs: [1],
buttonsNeeded: ["aOpen", "aClose", "strongOpen", "strongClose", "font", "size"],
classesNeeded: ["aText", "strongText", "sizeText"],
},
{
name: "Level 15",
textLines: 1,
htmlBuckets: [],
cssBlocks: 2,
cssSelectors: ["p", "div"],
cssPairs: [1, 1],
buttonsNeeded: ["background", "yellow", "color", "purple"],
classesNeeded: ["purpleText", "yellowText"],
},
]
